/******************************************************************************
 * Vige, Home of Professional Open Source Copyright 2010, Vige, and           *
 * individual contributors by the @authors tag. See the copyright.txt in the  *
 * distribution for a full listing of individual contributors.                *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may    *
 * not use this file except in compliance with the License. You may obtain    *
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0        *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 ******************************************************************************/
package it.vige.rubia.resttest.forumsearchmodule.test;

import static it.vige.rubia.dto.TopicType.NORMAL;
import static it.vige.rubia.search.SortBy.POST_SUBJECT;
import static java.util.Arrays.asList;
import static java.util.stream.Collectors.toList;
import static org.jboss.logging.Logger.getLogger;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Date;
import java.util.List;

import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;

import org.jboss.logging.Logger;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import it.vige.rubia.dto.CategoryBean;
import it.vige.rubia.dto.CategoryRequestBean;
import it.vige.rubia.dto.ForumBean;
import it.vige.rubia.dto.ForumInstanceBean;
import it.vige.rubia.dto.MessageBean;
import it.vige.rubia.dto.PollBean;
import it.vige.rubia.dto.PostBean;
import it.vige.rubia.dto.PosterBean;
import it.vige.rubia.dto.TopicBean;
import it.vige.rubia.resttest.RestCaller;
import it.vige.rubia.search.SearchCriteria;

public class SearchTest extends RestCaller {

	private final static String FORUMS_URL = "http://localhost:8080/rubia-forums-rest/services/forums/";
	private final static String SEARCH_URL = "http://localhost:8080/rubia-forums-rest/services/search/";
	private final static String authorization = "Basic cm9vdDpndG4=";

	private static Logger log = getLogger(SearchTest.class);

	private static Date firstDate;

	private static Date secondDate;

	private static Date thirdDate;

	private static Date forthDate;

	@BeforeAll
	public static void setUp() {
		log.debug("started test");
		ForumInstanceBean forumInstanceBean = new ForumInstanceBean();
		forumInstanceBean.setId(1);

		CategoryBean categoryBean = new CategoryBean("First Test Category");
		categoryBean.setForumInstance(forumInstanceBean);
		Response response = post(FORUMS_URL + "createCategory", authorization, categoryBean);
		CategoryBean category = response.readEntity(CategoryBean.class);

		ForumBean forumBean = new ForumBean("First Test Forum", "First Test Description", category);
		response = post(FORUMS_URL + "createForum", authorization, forumBean);
		ForumBean forum = response.readEntity(ForumBean.class);

		PostBean postBean = new PostBean("First Test Body");
		firstDate = new Date();
		postBean.setCreateDate(firstDate);
		TopicBean topicBean = new TopicBean(forum, "First Test Topic", asList(new PostBean[] { postBean }), NORMAL,
				null);
		PosterBean poster = new PosterBean("root");
		topicBean.setPoster(poster);
		topicBean.setPoll(new PollBean());
		response = post(FORUMS_URL + "createTopic", authorization, topicBean);
		PostBean post = response.readEntity(PostBean.class);
		topicBean = post.getTopic();
		postBean = new PostBean();
		postBean.setTopic(topicBean);
		postBean.setMessage(new MessageBean("First Test Post"));
		postBean.setPoster(post.getPoster());
		secondDate = new Date();
		postBean.setCreateDate(secondDate);
		post(FORUMS_URL + "createPost", authorization, postBean);

		thirdDate = new Date();
		postBean.setCreateDate(thirdDate);
		postBean.setMessage(new MessageBean("Second Test Post"));
		post(FORUMS_URL + "createPost", authorization, postBean);

		forthDate = new Date();
		postBean.setCreateDate(forthDate);
		postBean.setMessage(new MessageBean("Third Test Post"));
		post(FORUMS_URL + "createPost", authorization, postBean);
		response.close();
	}

	@Test
	public void search() {
		SearchCriteria searchCriteria = new SearchCriteria();
		searchCriteria.setKeywords("Third Test");
		Response response = post(SEARCH_URL + "findPosts", authorization, searchCriteria);
		List<PostBean> postBeans = response.readEntity(new GenericType<List<PostBean>>() {
		});
		assertEquals(4, postBeans.size());

		PostBean post = postBeans.get(0);
		assertNotNull(post);
		assertTrue(post.getAttachments().isEmpty());
		assertEquals(firstDate, post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		MessageBean message = post.getMessage();
		assertTrue(message.getBBCodeEnabled());
		assertTrue(message.getHTMLEnabled());
		assertTrue(message.getSignatureEnabled());
		assertFalse(message.getSmiliesEnabled());
		assertTrue(message.getSubject().isEmpty());
		assertEquals("First Test Body", message.getText());
		PosterBean poster = post.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		TopicBean topicBean = post.getTopic();
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		PollBean poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertFalse(topicBean.getPosts().isEmpty());
		assertEquals(4, topicBean.getPosts().size());
		post = topicBean.getPosts().get(0);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(1);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(2);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(3);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertTrue(topicBean.getWatches().isEmpty());
		ForumBean forumBean = topicBean.getForum();
		CategoryBean categoryBean = forumBean.getCategory();
		assertNull(categoryBean.getForumInstance());
		assertTrue(categoryBean.getForums().isEmpty());
		assertNotEquals(0, categoryBean.getId());
		assertEquals(20, categoryBean.getOrder());
		assertEquals("First Test Category", categoryBean.getTitle());
		assertNull(post.getUser());
		assertEquals("First Test Description", forumBean.getDescription());
		assertNull(forumBean.getForumWatch());
		assertNotEquals(0, forumBean.getId());
		assertEquals("First Test Forum", forumBean.getName());
		assertEquals(10, forumBean.getOrder());
		assertEquals(2, forumBean.getPostCount());
		assertFalse(forumBean.getPruneEnable());
		assertEquals(0, forumBean.getPruneNext());
		assertEquals(0, forumBean.getStatus());
		assertEquals(1, forumBean.getTopicCount());
		assertEquals(1, forumBean.getTopics().size());
		topicBean = forumBean.getTopics().get(0);
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertTrue(topicBean.getPosts().isEmpty());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertNull(topicBean.getWatches());
		assertNull(topicBean.getForum());
		assertTrue(forumBean.getWatches().isEmpty());

		post = postBeans.get(1);
		assertNotNull(post);
		assertTrue(post.getAttachments().isEmpty());
		assertEquals(secondDate, post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		message = post.getMessage();
		assertTrue(message.getBBCodeEnabled());
		assertTrue(message.getHTMLEnabled());
		assertTrue(message.getSignatureEnabled());
		assertFalse(message.getSmiliesEnabled());
		assertTrue(message.getSubject().isEmpty());
		assertEquals("First Test Post", message.getText());
		poster = post.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		topicBean = post.getTopic();
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertFalse(topicBean.getPosts().isEmpty());
		assertEquals(4, topicBean.getPosts().size());
		post = topicBean.getPosts().get(0);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(1);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(2);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(3);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertTrue(topicBean.getWatches().isEmpty());
		forumBean = topicBean.getForum();
		categoryBean = forumBean.getCategory();
		assertNull(categoryBean.getForumInstance());
		assertTrue(categoryBean.getForums().isEmpty());
		assertNotEquals(0, categoryBean.getId());
		assertEquals(20, categoryBean.getOrder());
		assertEquals("First Test Category", categoryBean.getTitle());
		assertNull(post.getUser());
		assertEquals("First Test Description", forumBean.getDescription());
		assertNull(forumBean.getForumWatch());
		assertNotEquals(0, forumBean.getId());
		assertEquals("First Test Forum", forumBean.getName());
		assertEquals(10, forumBean.getOrder());
		assertEquals(2, forumBean.getPostCount());
		assertFalse(forumBean.getPruneEnable());
		assertEquals(0, forumBean.getPruneNext());
		assertEquals(0, forumBean.getStatus());
		assertEquals(1, forumBean.getTopicCount());
		assertEquals(1, forumBean.getTopics().size());
		topicBean = forumBean.getTopics().get(0);
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertTrue(topicBean.getPosts().isEmpty());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertNull(topicBean.getWatches());
		assertNull(topicBean.getForum());
		assertTrue(forumBean.getWatches().isEmpty());

		post = postBeans.get(2);
		assertNotNull(post);
		assertTrue(post.getAttachments().isEmpty());
		assertEquals(thirdDate, post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		message = post.getMessage();
		assertTrue(message.getBBCodeEnabled());
		assertTrue(message.getHTMLEnabled());
		assertTrue(message.getSignatureEnabled());
		assertFalse(message.getSmiliesEnabled());
		assertTrue(message.getSubject().isEmpty());
		assertEquals("Second Test Post", message.getText());
		poster = post.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		topicBean = post.getTopic();
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertFalse(topicBean.getPosts().isEmpty());
		assertEquals(4, topicBean.getPosts().size());
		post = topicBean.getPosts().get(0);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(1);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(2);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(3);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertTrue(topicBean.getWatches().isEmpty());
		forumBean = topicBean.getForum();
		categoryBean = forumBean.getCategory();
		assertNull(categoryBean.getForumInstance());
		assertTrue(categoryBean.getForums().isEmpty());
		assertNotEquals(0, categoryBean.getId());
		assertEquals(20, categoryBean.getOrder());
		assertEquals("First Test Category", categoryBean.getTitle());
		assertNull(post.getUser());
		assertEquals("First Test Description", forumBean.getDescription());
		assertNull(forumBean.getForumWatch());
		assertNotEquals(0, forumBean.getId());
		assertEquals("First Test Forum", forumBean.getName());
		assertEquals(10, forumBean.getOrder());
		assertEquals(2, forumBean.getPostCount());
		assertFalse(forumBean.getPruneEnable());
		assertEquals(0, forumBean.getPruneNext());
		assertEquals(0, forumBean.getStatus());
		assertEquals(1, forumBean.getTopicCount());
		assertEquals(1, forumBean.getTopics().size());
		topicBean = forumBean.getTopics().get(0);
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertTrue(topicBean.getPosts().isEmpty());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertNull(topicBean.getWatches());
		assertNull(topicBean.getForum());
		assertTrue(forumBean.getWatches().isEmpty());

		post = postBeans.get(3);
		assertNotNull(post);
		assertTrue(post.getAttachments().isEmpty());
		assertEquals(forthDate, post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		message = post.getMessage();
		assertTrue(message.getBBCodeEnabled());
		assertTrue(message.getHTMLEnabled());
		assertTrue(message.getSignatureEnabled());
		assertFalse(message.getSmiliesEnabled());
		assertTrue(message.getSubject().isEmpty());
		assertEquals("Third Test Post", message.getText());
		poster = post.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		topicBean = post.getTopic();
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertFalse(topicBean.getPosts().isEmpty());
		assertEquals(4, topicBean.getPosts().size());
		post = topicBean.getPosts().get(0);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(1);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(2);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = topicBean.getPosts().get(3);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertTrue(topicBean.getWatches().isEmpty());
		forumBean = topicBean.getForum();
		categoryBean = forumBean.getCategory();
		assertNull(categoryBean.getForumInstance());
		assertTrue(categoryBean.getForums().isEmpty());
		assertNotEquals(0, categoryBean.getId());
		assertEquals(20, categoryBean.getOrder());
		assertEquals("First Test Category", categoryBean.getTitle());
		assertNull(post.getUser());
		assertEquals("First Test Description", forumBean.getDescription());
		assertNull(forumBean.getForumWatch());
		assertNotEquals(0, forumBean.getId());
		assertEquals("First Test Forum", forumBean.getName());
		assertEquals(10, forumBean.getOrder());
		assertEquals(2, forumBean.getPostCount());
		assertFalse(forumBean.getPruneEnable());
		assertEquals(0, forumBean.getPruneNext());
		assertEquals(0, forumBean.getStatus());
		assertEquals(1, forumBean.getTopicCount());
		assertEquals(1, forumBean.getTopics().size());
		topicBean = forumBean.getTopics().get(0);
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		poll = topicBean.getPoll();
		assertNull(poll.getCreationDate());
		assertNotEquals(0, poll.getId());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		poster = topicBean.getPoster();
		assertNotEquals(0, poster.getId());
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertTrue(topicBean.getPosts().isEmpty());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		assertNull(topicBean.getWatches());
		assertNull(topicBean.getForum());
		assertTrue(forumBean.getWatches().isEmpty());

		searchCriteria.setSortBy(POST_SUBJECT.name());
		response = post(SEARCH_URL + "findTopics", authorization, searchCriteria);
		List<TopicBean> topicBeans = response.readEntity(new GenericType<List<TopicBean>>() {
		});
		assertEquals(1, topicBeans.size());
		topicBean = topicBeans.get(0);
		assertNotNull(topicBean);
		assertNotEquals(0, topicBean.getId());
		assertEquals(forthDate, topicBean.getLastPostDate());
		assertEquals(1, topicBean.getReplies());
		assertEquals(0, topicBean.getStatus());
		assertTrue(topicBean.getSubject().isEmpty());
		assertEquals(NORMAL, topicBean.getType());
		assertEquals(0, topicBean.getViewCount());
		ForumBean forum = topicBean.getForum();
		CategoryBean category = forum.getCategory();
		assertNull(category.getForumInstance());
		assertTrue(category.getForums().isEmpty());
		assertNotEquals(0, category.getId());
		assertEquals(20, category.getOrder());
		assertEquals("First Test Category", category.getTitle());
		assertEquals("First Test Description", forum.getDescription());
		assertNull(forum.getForumWatch());
		assertNotEquals(0, forum.getId());
		assertEquals("First Test Forum", forum.getName());
		assertEquals(10, forum.getOrder());
		assertEquals(2, forum.getPostCount());
		assertEquals(1, forum.getTopicCount());
		assertEquals(false, forum.getPruneEnable());
		assertEquals(0, forum.getPruneNext());
		assertEquals(0, forum.getStatus());
		assertTrue(forum.getWatches().isEmpty());
		List<TopicBean> topics = forum.getTopics();
		assertEquals(1, topics.size());
		assertEquals(topicBean, topics.get(0));
		poster = topicBean.getPoster();
		assertEquals(0, poster.getPostCount());
		assertEquals("root", poster.getUserId());
		assertNotEquals(0, poster.getId());
		poll = topicBean.getPoll();
		assertNotEquals(0, poll.getId());
		assertNull(poll.getCreationDate());
		assertEquals(0, poll.getLength());
		assertTrue(poll.getOptions().isEmpty());
		assertNull(poll.getTitle());
		assertTrue(poll.getVoted().isEmpty());
		assertEquals(0, poll.getVotesSum());
		List<PostBean> posts = topicBean.getPosts();
		assertEquals(4, posts.size());
		post = posts.get(0);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = posts.get(1);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = posts.get(2);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		post = posts.get(3);
		assertTrue(post.getAttachments().isEmpty());
		assertNull(post.getCreateDate());
		assertEquals(0, post.getEditCount());
		assertNull(post.getEditDate());
		assertNotEquals(0, post.getId());
		assertNull(post.getMessage());
		assertNull(post.getPoster());
		assertNull(post.getTopic());
		assertNull(post.getUser());
		response.close();
	}

	@AfterAll
	public static void stop() {
		log.debug("stopped test");

		Response response = get(FORUMS_URL + "findCategories/1", authorization);
		List<CategoryBean> categoryBeans = response.readEntity(new GenericType<List<CategoryBean>>() {
		});

		CategoryRequestBean categoryRequestBean = new CategoryRequestBean();
		categoryRequestBean.setCategory(categoryBeans.stream().filter(x -> x.getTitle().equals("First Test Category"))
				.collect(toList()).get(0));
		categoryRequestBean.setLimit(3);

		response = post(FORUMS_URL + "findPostsFromCategoryDesc", authorization, categoryRequestBean);
		List<PostBean> postBeans = response.readEntity(new GenericType<List<PostBean>>() {
		});
		assertEquals(3, postBeans.size(), "Posts size");

		response = get(FORUMS_URL + "removePost/" + postBeans.get(0).getId() + "/false", authorization);
		response = get(FORUMS_URL + "removePost/" + postBeans.get(1).getId() + "/false", authorization);
		response = get(FORUMS_URL + "removePost/" + postBeans.get(2).getId() + "/true", authorization);

		response = post(FORUMS_URL + "findPostsFromCategoryDesc", authorization, categoryRequestBean);
		postBeans = response.readEntity(new GenericType<List<PostBean>>() {
		});

		response = get(FORUMS_URL + "findTopics/1", authorization);
		List<TopicBean> topicBeans = response.readEntity(new GenericType<List<TopicBean>>() {
		});
		PosterBean posterBean = topicBeans.get(0).getPoster();

		topicBeans.forEach(x -> {
			get(FORUMS_URL + "removeTopic/" + x.getId(), authorization);
		});
		response = get(FORUMS_URL + "findTopics/1", authorization);
		topicBeans = response.readEntity(new GenericType<List<TopicBean>>() {
		});

		response = get(FORUMS_URL + "removePoster/" + posterBean.getId(), authorization);
		PosterBean removedPosterBean = response.readEntity(PosterBean.class);

		response = get(FORUMS_URL + "findPosterByUserId/" + removedPosterBean.getUserId(), authorization);
		posterBean = response.readEntity(PosterBean.class);

		response = get(FORUMS_URL + "findForums/1", authorization);
		List<ForumBean> forumBeans = response.readEntity(new GenericType<List<ForumBean>>() {
		});

		response = get(FORUMS_URL + "findCategories/1", authorization);
		categoryBeans = response.readEntity(new GenericType<List<CategoryBean>>() {
		});

		get(FORUMS_URL + "removeForum/" + forumBeans.get(1).getId(), authorization);
		get(FORUMS_URL + "removeCategory/" + categoryBeans.get(1).getId(), authorization);
		response.close();
	}
}
